### ISSUE TITLE
Otago issue 1: Features obscuring units

### ISSUE THREAD

**Issue by ghost** [beyond-all-reason/Beyond-All-Reason#1075]
Some time spent with the Otago remake has revealed 2 game issues that make it and maps like it suboptimal.

There is currently no way to perceive units behind features without selection or zooming to unit icons. Ambushes from a thick cluster of forest could be an interesting game mechanic if it wasn't as easy to lose track of one's own units in the forest. 

I see talk of hopes of maps like the ruined urban maps of OTA days and this issue will inevitably affect maps like those. Like thick forests, tall and large industrial buildings or ruins get massively less fun when all units are obscured behind at a non-vertical angle.

Enemy units should be visible behind features too, but only within LOS.

**Comment by Beherith** [comment]
The issue here is that the rendering pipeline is not set up to fully support this. Especially the problem of detecting wether a unit is obscured is very difficult.

**Comment by SethDGamre** [comment]
If this isn't a plant feature, can this be closed?

**Comment by AntlerForce** [comment]
I think this can be closed. I have already made the trees on Otago significantly smaller to work around this issue so it isn't much of a problem on that map anymore.

Showing units obscured by features somehow is more of a pie-in-the-sky feature request, while in this ticket the issue is framed as a bug.
