### ISSUE TITLE
White looking grass outside of los when spectating on AMD/Linux

### ISSUE THREAD

**Issue by MooseOnTheLoose** [beyond-all-reason/Beyond-All-Reason#1092]
https://cdn.discordapp.com/attachments/549282926596980738/997558500278415532/screen00128.png

> Beherith — Today at 2:18 PM
oooh ticket this one, it seems that its not los view, but los sensor rings stencils!

**Comment by Beherith** [comment]
Since i gotta fix this blind, i need a bit more info: are there any triggers or is it constant? Does disabling any/all sensor ranges widgets change this? Its wierd how it seems to be ok with radar which is a nigh identical widget.

**Comment by Beherith** [comment]
Did the bug appear recently?

**Comment by The-Yak** [comment]
It's triggered by being a spectator and selecting a unit. it is constant throughout the game and never goes away. 

It does not only occur to selected units, just selecting anything makes the effect appear everywhere.

It did not recently appear, has always been an issue since I returned. just slow to report because I knew it was probably amd/linux only.

F5 gets rid off it. LOS toggle key does not. What widgets should I turn on/off to test?

**Comment by The-Yak** [comment]
It also goes away when zoomed beyond grass LOD.

**Comment by The-Yak** [comment]
![screen00146](https://user-images.githubusercontent.com/1368663/185712566-fc42927d-31b3-4ba6-9b02-e41f60c79c80.png)
![screen00147](https://user-images.githubusercontent.com/1368663/185712574-47173176-82fe-4897-8fe5-eb385bf8b5f0.png)

I can see this occur with more than just grass.

**Comment by MooseOnTheLoose** [comment]
![screen00012](https://user-images.githubusercontent.com/1368663/193471481-a4ec4cac-41d9-4db1-a94d-423f72b836ac.png)

This issue is now resolved for me.

**Comment by Beherith** [comment]
oh man is one is wierd, its actually ground_ao_plates_features, im glad its fixed tho
