### ISSUE TITLE
Ships don't look nearly as ships

### ISSUE THREAD

**Issue by Tarek-Hasan** [beyond-all-reason/Beyond-All-Reason#1145]
Like other Total Annihilation derived games (except NOTA), BAR also inherited a not so intimidating navy. Its naval force looks like a speedboat gang or at the very best a rich guy's personal yacht force with big guns attached to those. The problem, better explained by NOTA developers [here](https://springrts.com/wiki/NOTA_OTA_differences_guide#What.27s_so_different_about_NOTA_navy.3F).
You can look at their ship models for references and better understanding in following page.
http://nota.machys.net/nota-units
https://bitbucket.org/notagame/nota/src/master/
Ships are a big part of military might and a catalyst in turning the tide of war. Please let ships, war machines with thousands of years of history live up to their names.

**Comment by Beherith** [comment]
Feel free to improve them, here is how: https://trello.com/c/7me8AdgO/74-unit-3d-model-workflow

**Comment by Beherith** [comment]
whoops accidental close

**Comment by badosu** [comment]
Giving ships more firepower than they have at the moment would just exacerbate the issue that ships already have in the current iteration: snowballing. A lot of thought has been put to make sure that sea is just as playable as land, and making ships more powerful - thereby increasing their cost - counters that goal.

If the issue is related to the models themselves then I guess it's a matter of subjective judgement, otherwise I don't see a reason for this issue to remain open.

**Comment by SethDGamre** [comment]
Old issue which is more of a suggestion. Hop on the suggestions channel on discord to propose changes to the game. Grab a dev role therein and find resources to model things yourself!
