### ISSUE TITLE
Why are some Fusion Plant's hit points hidden?

### ISSUE THREAD

**Issue by Rhade1** [beyond-all-reason/Beyond-All-Reason#1299]
armfus, armuwfus, corfus, coruwfus have `hidedamage = true` in their definition files.
armckfus, armafus and corafus do not.
Is there a reason?

**Comment by Borg-King** [comment]
If I remember correctly, this is a vestige of when seeing the health bars of enemy fusions could tell you whether they were decoy fusions or not. Kind of redundant now I suppose as I don't think decoy fusions are even built (or ever were??)

**Comment by Beherith** [comment]
Heh decoys, also, these are moot since damage based shading :D

**Comment by Rhade1** [comment]
> damage based shading :D

Is it visible even if `Advanced Model Shading` is turned off?
Why not add `hidedamage = true` to everything then?

> If I remember correctly, this is a vestige of when seeing the health bars of enemy fusions could tell you whether they were decoy fusions or not.

Decoys should have the same HP then... As for Decoy Commander, maybe should not have different abilities or buildoptions either.
Besides, underwater fusions and corfus have no decoys.

**Comment by Beherith** [comment]
Advmodelshading off is not a supported game mode. Ill have to remove it
from settings.

**Comment by WatchTheFort** [comment]
How often are decoys actually used, especially by high level players?

**Comment by Beherith** [comment]
I use them whenever I forget to play as Cortex in FFA games.

**Comment by Rhade1** [comment]
> How often are decoys actually used, especially by high level players?

Personally, I would not miss decoy fusion plants, however this topic is more about design choices.
I often heard that _Commander's hit points are hidden_, but never that _Commander's, Fusion Plant's and some other objects hit points are hidden_...

**Comment by Ruwetuin** [comment]
if the reason it is this way to not expose max unit health stuff then I suppose an engine change to support decoy units reporting back the health it would have had as if it was a non decoy version (for non allies)

**Comment by sprunk** [comment]
that already happens for decoys if they don't have hidden health iirc?

**Comment by WatchTheFort** [comment]
So it sounds like there isn't really a reason for fusions and decoys have their health hidden.

**Comment by sprunk** [comment]
not necessarily, unless the units have the same health you can still tell it's a decoy when damaged (for example if the real unit has twice the health of a decoy then shots will appear to do twice the nominal damage)

**Comment by Ruwetuin** [comment]
> Not necessarily, unless the units have the same health you can still tell it's a decoy when damaged (for example if the real unit has twice the health of a decoy then shots will appear to do twice the nominal damage). But if a fusion is taking damage it's probably going down regardless and you need to pay a lot of attention to notice so it may well be fine (skill ceiling and all).

my comment was exactly about this though, so your last comment seems to contradict, am confused

**Comment by WatchTheFort** [comment]
Why would decoys not have the same health as their real counterpart? Isn't the point that they're cheap, not that they're harder to destroy?

**Comment by sprunk** [comment]
I thought your comment was just that there should be *some* health translation function so that if there's a real unit with 100 health and a decoy with 50, it should display 100/100 instead of 50/50 initially, which would be sufficient for fusions (since they are usually in a safe spot so are almost always at full health) and which already happens.

But you seem to want to go further and have a translation function that would not betray the decoy so easily on damage. Making the decoy display 90/100 while at 40/50 (ie. upon taking 10 damage) would probably work slightly better than the 80/100 it would display currently but then you would have to handle edge cases:
 * what if the decoy has 200 health instead and somebody deals 110 damage? You probably shouldn't display -10/100. Do you reveal the decoy? Do you track which allyteams have seen the damage exceed the proper value (since decoy is mostly for FFA)?
 * what about repair if the decoy has a different buildtime, do you also track repair/reclaim damage and scale the value so it looks like it was real?
 * what about EMP? It works on max hp so also reveals a decoy with every shot.

IMO the current proportional method works mostly good enough and I'm not sure if the engine should be the one to answer how to handle some of these. Straying a bit into engine discussion, maybe there should be some sort of `gadget:GetDecoyHealth(unitID, decoyDefID, realDefID)` that returns the current health so ZK could stick with the proportional method:
```lua
local realMax = 100
local decoyMax = 200
local unitHealth = 90
return unitHealth * (realMax  / decoyMax ) -- "45/100", in reality 90/200
```
while BAR would try and figure out how to do it sensibly the other way:
```lua
local realMax = 100
local decoyMax = 200
local unitHealth = 90

local damageTaken = decoyMax - unitHealth -- 110
if damageTaken < realMax then
  return realMax - damageTaken -- but also +repair etc, see above
else -- oops, can't do "-10/100"!
  -- lol what now? complicated allyteam tracking and/or some magic reveal logic goes here
end
```

**Comment by sprunk** [comment]
> Why would decoys not have the same health as their real counterpart? Isn't the point that they're cheap, not that they're harder to destroy?

The point is that they are a bait that draws enemies and then draws fire. Being cheaper is necessary (since otherwise you may as well get a real one and have it be productive) but having more health helps them draw fire for longer before dying (as long as the enemy doesn't realize it's a decoy; that point may well be beyond the point at which a real unit would have died already).

**Comment by SethDGamre** [comment]
This issue hasn't received attention in two years.
