### ISSUE TITLE
Default fog of war darkness a bit too dark

### ISSUE THREAD

**Issue by TLWmarko** [beyond-all-reason/Beyond-All-Reason#132]
If you don't know the levels it's quite difficult to see the layout when it's unexplored, since on maps with for example grass the fog of war makes the grass almost black. I recently learned about the L button for toggling it, but only after finding the discord and asking. Would be super neat if the darkness level or effect was adjustable! Maybe even with desaturation to make it stand out in a different way even when less dark?

**Comment by icexuick** [comment]
Since we chose not to use colors, we've been tweaking the LOS colors for quite some time.
It's very hard to have only brightness, and later we added the diagonal lines to get an extra layer (non-radar) in there as well.
Also some maps are 'darker' and it's hard to make the LOS colors work for all maps.

You can also disable one layer in the LOS view with the ` ;  `key.
This will lighten everything a bit, but you will lose a layer in the LOS system.
But this could help you see more, or toggle it back on for brighter maps.

**Comment by icexuick** [comment]
@lhog can we live-change fog of war opacity in-game?

**Comment by lhog** [comment]
> 
> 
> @lhog can we live-change fog of war opacity in-game?

Yes, these colors are overridable https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/shaders/GLSL/infoLOS.lua#L20-L24

**Comment by SethDGamre** [comment]
Is this issue resolved?

**Comment by SethDGamre** [comment]
issue is ancient, I don't see the darkness issue anymore. If this is still a problem, @ me and I'll reopen
