### ISSUE TITLE
Hound stops moving and loses command queue with weapon toggle

### ISSUE THREAD

**Issue by resopmok** [beyond-all-reason/Beyond-All-Reason#1333]
When the weapon type plasma -> gauss or gauss -> plasma is triggered, Hound loses it's current queue of orders (it seems a stop command is issued at the same time). This appears to be buggy behavior, as Vanguard, a unit which toggles trajectory, does not stop or lose targets or other commands in queue  when it is toggled. For Hound, it may be desirable to require the unit to stop moving while the weapon change animation takes place, but it at least shouldn't lose it subsequent command queue at the same time.

**Comment by WatchTheFort** [comment]
@KyleAnthonyShepherd Do you think this is another case of continuous aim bugs?

**Comment by KyleAnthonyShepherd** [comment]
Made a PR here
https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1343
armfido has a gadget that controls some range behavior for weapon swaps. This gadget also sends in wait commands, messing up the hound orders. 
The PR just turns off this gadget. Did some tests, unit does not stutter on toggle, and otherwise seems to have the same behavior. I think the gadget is just obsolete, from a previous method of weapon switching.

**Comment by Beherith** [comment]
Fixed by Itanthias :)
