### ISSUE TITLE
Ctrl+z sometimes bugging out

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#1470]
Have just switched to using Bar Hotkeys via Control -> Keybindings -> Custom and am now getting this issue. I'm currently using the defaults though and haven't touched the file yet.

https://user-images.githubusercontent.com/1434248/210076320-436a9231-00ed-47ca-91e7-33114cbe26ec.mp4

This video shows the following behaviour when I issue these actions:

1. Drag a selection box to select the pawn
2. Hold Ctrl
3. Tap z (should select all pawns at this point)
4. Left click anywhere on the map to clear the selection

Expected: All pawns are selected

Actual: Works most of the time, but occassionally it will do nothing and left clicking no longer clears the selection. Ctrl+z also does nothing at this point. Have to click another unit in order to deselect the pawn.

**Comment by Jazcash** [comment]
@badosu Confirmed it's an issue with smart select because disabling that widget fixes the problem

**Comment by badosu** [comment]
@Jazcash I can't reproduce, can you please post uikeys.tmp on bar root after `/keysave`?

**Comment by Jazcash** [comment]
> @Jazcash I can't reproduce, can you please post uikeys.tmp on bar root after `/keysave`?

I deleted them already, no longer have any uikeys files of any kind

**Comment by badosu** [comment]
Are you still able to reproduce? If so, just `/keysave` and please post uikeys.tmp on bar root folder.

If not, I can't confirm it's a bug and can't reproduce myself to attempt a fix.

**Comment by Jazcash** [comment]
> Are you still able to reproduce? If so, just `/keysave` and please post uikeys.tmp on bar root folder.
> 
> If not, I can't confirm it's a bug and can't reproduce myself to attempt a fix.

[uikeys.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/10324982/uikeys.txt)

**Comment by badosu** [comment]
Is this the file that was named `uikeys.tmp` on bar root folder that was generated after `/keysave` and a successful reproduction?

**Comment by Jazcash** [comment]
> Is this the file that was named `uikeys.tmp` on bar root folder that was generated after `/keysave` and a successful reproduction?

Yup exactly that

**Comment by badosu** [comment]
Thank you, I was able to reproduce.

**Comment by badosu** [comment]
Just for reference, this is unrelated to ctrl+z. The bug can be reproduced by holding ctrl _before_ and only releasing _after_ the selection is performed (mouserelease)

**Comment by badosu** [comment]
Ok, I identified this as an engine issue, I'll fix it there, thanks for reporting!

**Comment by badosu** [comment]
Well, I simply can't compile engine locally (due to missing 7z headers and can't find a decent source for headers). Due to this circumstance I can't diagnose why the new engine displays the issue with the old does not (I can't rule out this might still be a game side issue).

See also: https://github.com/beyond-all-reason/spring/issues/560

**Comment by badosu** [comment]
@p2004a Above comment seems related to this: https://github.com/beyond-all-reason/spring/commit/4e0f711cf49c2404766ec46274dad5d1c53392a4

Do you know where I can download the headers required in the commit above? (They were vendored before, they're not anymore)

**Comment by badosu** [comment]
Ok, after extensive bisecting and debugging I found out it comes as an issue with many causal factors:

- Engine defined Ctrl modifier to remove from selection [here](https://github.com/beyond-all-reason/spring/blob/5d96d092b3318ddfb8bcdb7eae656e7887c02c4b/rts/Game/SelectedUnitsHandler.cpp#L293-L296)
- The fact smartselect has to depend on stupid mouseowner behavior hardcoded into engine so it can't distinguish an active selection box from an inactive one, in this case using `Update` instead of being able to figure that out with `MouseRelease`
- The fact I made `Spring.GetSelectionBox` not return the selection box if there is no current valid selectionbox.

What happens is:

1. Ctrl activates deselection mode hardcoded in engine
2. Unit is correctly selected by smartselect widget when dragging selection
3. When mouse is released (with ctrl pressed), the engine deselects the units internally **however** smartselect widget does not allow `SelectionChanged` callin to propagate while having a corrupt selection itself.
4. Now because the mouse was released and there is no actual valid selection anymore smartselect does not update the selection to contain the units inside selection box. (since we changed `GetSelectionBox` to return nil when there is no active selection box)
4. Everything turns to shit due to this desync in state between widgets and engine

There are a few reasonable solutions to this problem, for now I'll rely on fixing this on smart select itself. There are some other solutions and problems related to this issue I want to investigate further later, but basically:

- Engine hardcoded modifier for ctrl pressed to act as deselection, this should be unhardcoded and smartselect widget on activation should disable all hardcoded modifiers related to selection (since it performs its own logic).
- Fucking stupid MouseRelease ownership hardcoded into the engine, it just propagates events if you return true as the owner.
- Alternatively consider an actual selection changed callin instead of the current hacky one piggybacked on `CommandsChanged` by widget manager. When it returns true we indicate that we are performing the selection ourselves and avoid engine selection handler.

**Comment by Jazcash** [comment]
I believe this issue is back, happening for me again, only with SmartSelect enabled

**Comment by Jazcash** [comment]
@badosu
https://user-images.githubusercontent.com/1434248/218157885-691ce45c-81d0-4e9f-9b0b-1a8dac30daf2.mp4

As you said, holding ctrl before releasing the selection box repros the issue

**Comment by badosu** [comment]
Yeah, there's a multipart fix for this. The actual fix is to untie engine hardcoded deselection modifier, i have a first part for that on https://github.com/beyond-all-reason/spring/pull/562 but I'm having a hard time deciding on whether to merge it or discuss further to convince others of its necessity.

The other approach is to try and fix it in the widget itself, which I started on https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1473 but its not an actual fix and didn't find the proper gateway to fix it lua side.

The nuclear option is to revert the smartselect widget to its original behavior which does not use `Spring.GetSelectionBox`, and honestly probably the more sensible course of action if this is a prevalent issue.

I'll try fixing this in this weekend with the methods I have available, if none works I'll do the nuclear option until I am able to finally unhardcode ctrl+ modifier from deselect.

Thanks again for bringing this to my attention.

**Comment by badosu** [comment]
Resolved in https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1538. Would appreciate if someone could test this before merging, thanks.

**Comment by badosu** [comment]
Resolved, bugged then fixed. This can be closed now.
