### ISSUE TITLE
Set target command: No line drawn if target is a radar dot (unknown unit)

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1486]
https://youtu.be/ZYCU8l8aXbg

**Comment by SethDGamre** [comment]
things are different since this was posted originally

set target doesn't work if you click settarget button from the UI buttons and then click the undiscovered unit. This must be because it's an unknown target and so it cannot be prioritized. However, if you have set target as default right click instead of attack, it will revert to attack when you right click it instead of set target.
![image](https://github.com/user-attachments/assets/68991b32-ed25-4b07-af2e-91f9af8fe90e)

This isn't perfect, but, it's servicable IMO.

**Comment by SethDGamre** [comment]
Combining into the above as I believe they're both related to not exposing unitID's to unsynced space.
