### ISSUE TITLE
Radar dots cannot to be targeted sometimes

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/Beyond-All-Reason#1488]
Conditions: Target unit is small and radar dot deviated from real unit position far.

https://youtu.be/ehy28yOQ8_k

**Comment by SethDGamre** [comment]
specifically, targetting via attack/set target commands cannot happen via clicking when the unit is outside radar range. Though, the dots show up. Those dots ARE targettable automatically by automatic means E.G weapon on fire at will no matter the range so long as the dot shows up and is within weapon range.

**Comment by SethDGamre** [comment]
Requesting review to determine the best way to fix this.

**Comment by saurtron** [comment]
Regarding this issue, not very sure about the description or what's going on. If the dots are outside of radar range how do they show up?

For cases of buildings that actually leave a radar trace outside of radar range I can see attack doesn't allow targeting, either through circle or direct click. For radar dots when inside radar range seems to work fine.

This can be investigated, but I think it's something that can also affect balance, also a possible problem might be that you can have a radar trace but the building already be destroyed, so allowing targeting there can be problematic since it has to be done in a way not to leak information to players (likely this is why it's not implemented atm).

If everyone agrees they should be targeted then at some point the issue can be investigated, but currently it's not clear if it's actually wanted.

**Comment by SethDGamre** [comment]
> Regarding this issue, not very sure about the description or what's going on. If the dots are outside of radar range how do they show up?

What's going on is the actual position of the unit is inside of radar range, but radar wobble causes them to drift in and out of radar range. When outside of radar range, they are not targetable.

At least that's what I remember from the issue

**Comment by saurtron** [comment]
Ok I understand now. I noticed too, area command doesn't seem to select based on the radar dot, but on the actual unit position, might be related.

**Comment by saurtron** [comment]
I think I know what's going on, it's not related to going out of radar range, but going out of Quad (internal buckets where units are placed to simplify collision detection).

GetQuadsOnRay doesn't return the quad where the units are and thus they aren't detected on mouseover or click.

On the other hand the circular selection fails because it doesn't take into account the radar wobble so just selects based on real position.
