### ISSUE TITLE
Lunkhead :: Sonar Range 550 (sonar doesn't work)

### ISSUE THREAD

**Issue by Ezahiel** [beyond-all-reason/Beyond-All-Reason#1493]
Issue with armlun - Lunkhead :: Sonar Range 550 yet sonar doesn't work. Can only target not subs(as per params) so underwater buildings , yet Sonar doesn't work 😄 as per screens stand above uw buildings (with so called own sonar 550) then fire when brought Air sonar 😄 So sonar on Lunkhead(T3 Hover) doesn't work, or am i missing something ?
![screen00096](https://user-images.githubusercontent.com/114177265/213692873-bc219486-a747-4341-a46e-4fb2424db2d3.png)
![screen00097](https://user-images.githubusercontent.com/114177265/213692882-edded8f0-6750-4e0e-afe2-8fbd800b998f.png)

**Comment by Ezahiel** [comment]
seems same problem with counterpart Cortex (corsok) Cataphract, even thought both shows Sonar it doesn't work on either hehe
![image](https://user-images.githubusercontent.com/114177265/216202710-441a9d5e-4e6f-45a1-9bcc-519f24237d5a.png)

**Comment by KyleAnthonyShepherd** [comment]
Bleh, there is such a dumb reason why sonar is not working for T3 hovers. 
Because, it also turns out radar does not work on these units
activatewhenbuilt = true,
This needs to be in the unitdef
The unit needs to be "activated" to use sonar and radar.
Not sure on the underlying "why", but every other (working) radar and sonar unit have this line
