### ISSUE TITLE
Replay speed slower than displayed speed, real life speed

### ISSUE THREAD

**Issue by Corosauce** [beyond-all-reason/Beyond-All-Reason#1599]
If I choose 1x speed, I find it takes about 64 seconds to plays 60 seconds of a replay.

This may come across as a nitpick but its fun to sync up a replay with a video of someone playing, this may be a side effect of providing a replay of every game ever played which I am forever grateful is a thing from this amazing team of developers.

Motivation:
The game is getting more popular, id like to watch my favorite person play the game while I also watch their replay in the game so I can see what else is going on in the match that they are not covering.

Steps to reproduce:
- play a replay
- start a stopwatch
- stop it 1 minute after according to ingame time

I don't think my pc is too slow causing the issue, as it is a very recent fairly high end pc, I can choose 10x speed and it seems to be progressing at least 4 ingame seconds per real life seconds.

Specs:

Device name	Corobox
Processor	13th Gen Intel(R) Core(TM) i5-13600K   3.50 GHz
Installed RAM	32.0 GB DDR4 (31.8 GB usable)
GPU:                AMD 6800 XT

**Comment by SethDGamre** [comment]
I have a PC with a 1650ti and some kind of mid tier AMD gaming processor. From my  experimentation, running at 1x speed I had perfect synchrony. I just alt-tabbed and when I came back there was a slight desync of 2 seconds loss. This is due to performance hit from running in background.

I would chock this issue to performance stutters causing slight time desync on user-side. I don't see this being fixed or changing any time soon. I'd close the issue, myself.
