### ISSUE TITLE
Translation updates can break game

### ISSUE THREAD

**Issue by p2004a** [beyond-all-reason/Beyond-All-Reason#1652]
It looks like https://github.com/beyond-all-reason/Beyond-All-Reason/pull/1647 broke the game and had to be hot fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/35c043a937bdbcc745fa8084c2e3ecde23db2e33

I don't see any issue about that so opening one for @WatchTheFort to prevent it happening in the future.

**Comment by WatchTheFort** [comment]
Here's what happened:

- Transifex picks up the Github JSON file to serve as the source of translation strings
- When loading the strings, it silently converts single-space whitespace strings to empty strings (it is not known whether it is just single spaces or any whitespace-only string)
- Empty strings do not show up in the translation editor, so translators aren't even aware of them
- When transifex writes the translated JSON file to merge to Github, it includes the empty strings
- Our I18N library does not like this, which is why these strings are single spaces in the first place
- We have previously tried using the `\0` null terminating character for this, but JSON does not like that

I have opened a support ticket on Transifex, and will update this issue when I hear back

**Comment by sprunk** [comment]
Don't replace empty strings with `\0`, just make i18n not blow up on empty strings.

**Comment by WatchTheFort** [comment]
I commented out the empty string check and it looks like everything just works, and it turns out the I18N library has supported empty strings this whole time.

**Comment by WatchTheFort** [comment]
I18N now supports empty strings.

**Comment by WatchTheFort** [comment]
Need to check if this breaks fallback for missing translation keys.

**Comment by sprunk** [comment]
Why would it allow them? An empty string is almost never valid, hides the fact there's even text there (making it harder to notice something is wrong) and it's what tools produce for untranslated strings.

**Comment by WatchTheFort** [comment]
There are cases where dynamic I18N key lookups need to be used, particularly for unit descriptions.
`Spring.I18N('units.descriptions.' .. unitDefName)`.

However, not all units have descriptions, so no-op strings (empty, `\0`, `\u0000`) were used in these places. This is because trying to look up an I18N key that doesn't exist logs an error, and we want to be able to distinguish these cases where the description should be blank from genuine cases where the description is missing.

I will try to implement a solution that removes these empty I18N entries, and tag I18N exempt items that use dynamic key lookups to do something else.

**Comment by sprunk** [comment]
>not all units have descriptions

Can you actually get in a situation where a descriptionless unit is supposed to have its description shown? For example I see that the tacnuke spawner has no description. This sounds like a technical unit that should never have its tooltip shown outside of development (and even during development really), so accordingly there should be nothing to trigger the error.

> removes these empty I18N entries, and tag I18N exempt items that use dynamic key lookups to do something else

Perhaps the error could just be moved to a higher layer. The library would not put any warnings and just return `nil` for empty strings, and you'd have a bunch of functions to control the desired behaviour.
```lua
function Spring.I18N(key)
  local ret = i18n_internal(key)
  if not ret then
    Spring.Echo("warning, key missing", key)
    ret = key
  end
  return ret
end

function Spring.I18N_optional(key)
  return i18n_internal(key) or  ""
end

function Spring.I18N_default_to_english(key)
  local ret = i18n_internal(key)
  if not ret then
    Spring.Echo("warning, key missing", key)
    ret = i18n_internal(key, "en")
  end
  return ret
end

... etc
```

**Comment by WatchTheFort** [comment]
In the end I went the opposite direction, and added descriptions to units that were missing them, added missing faction tooltips, and deleted entries for settings tooltips.

I have not yet reverted the changes to the I18N init.lua file, as the German translations must be updated first to fill out the missing captions.

**Comment by WatchTheFort** [comment]
If Github could go ahead and give us the ability to _not_ auto-close an issue when merging a linked pull request, that would be great.

**Comment by sprunk** [comment]
How are you linking the PR? IME if you just name-drop the ticket in the PR, the PR appears in the ticket but won't close it.

**Comment by sprunk** [comment]
Look, I just made a PR and it appears above but did not close this ticket.

**Comment by WatchTheFort** [comment]
So in the end, empty strings are not allowed, and all empty strings have been removed or filled out.
