### ISSUE TITLE
need to rebalance metal and energy storage

### ISSUE THREAD

**Issue by CopyyyCattt** [beyond-all-reason/Beyond-All-Reason#173]
at the moment these buildings are almost useless.
Some(or all) storage capacity needs to be taken away from metal producing and energy producing buildings.

**Comment by Jazcash** [comment]
Energy storage is useful if you're mainly using windmills, because it creates a bigger buffer to wind speed changes. Also useful if you're using units that require a lot of energy. Anything that cloaks, tachyon weapons, dgun, vulcan/buzzsaw etc.

Metal storage is always useful if you're over-producing or reclaiming lots of wreckages because you don't want to overflow and lose the metal to the ether, or even worse, share it with your team
