### ISSUE TITLE
downloader loosing progress [feedback]

### ISSUE THREAD

**Issue by krznowicki** [beyond-all-reason/Beyond-All-Reason#1816]
with bad internet connection, the downloader seems to loose progress;

Description - I was downloading the game, the connection was slow, so it took some time. When my connection got disconnected and reconnected, the progress dropped from 50% to 11% (I'm aware that after you go out of installer and restart the download, the downloader recomputes the size to be downloaded; _this is not it_, as the total size didn't change, It simply lost progress).

Related log is here: https://log.beyondallreason.dev/logs-20230529T1048-OIhQalZY.zip
\<edit\>: example can be found close to the end, where the progress drops from ~50% to ~16%)  \</edit\>

My guesses - either downloader reports progress before it has whole chunk of data, and when it gets disconnected, it scraps the progress on unfinished chunks or you actually loose data because of some unspecified bugs. 

PS: maybe that is not specific enough to go to github, but I'm too lazy to figure out how to make 2 discord acocunts on one phone number; still wanted report something that looks like a potential bug. @team, feel free to scrap the issue after you read it.

**Comment by p2004a** [comment]
All looks fine. All the drops are because of failure, and after each drop, so also reset of downloading, the total in next retry was almost exactly on point with what it's supposed to be

![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/2212599/c88b8276-b443-40fc-8907-430387cb9b4e)

it's expected that there are small differences, and very small portions of data need to be refetched, which is visible also on percentages.
