### ISSUE TITLE
High Trajectory targeting bug

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#1908]
High Trajectory mode 'locks' outside range targets (aims them) then dont change to in-range targets as they arrive.

Low Trajectory works as expected.

[20230629_120335_All That Glitters v2_105.1.1-1767-gaaf2cc3 BAR105.sdfz.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/11905488/20230629_120335_All.That.Glitters.v2_105.1.1-1767-gaaf2cc3.BAR105.sdfz.zip)

**Comment by KyleAnthonyShepherd** [comment]
Yup, saw this exact bug on the corhllt.
It is due to a bad interaction between a negative `proximitypriority` (in this case -2) and the default pre-aim at units 10% out of range `autoTargetRangeBoost` being set in this gadget
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luarules/gadgets/unit_preaim.lua

The bad interaction is the unit preferring to aim at out of range targets it cannot actually fire at. 

The proper fix would be done engine-side, and sort units beyond 100% range to the bottom of the priority list. 
But gameside, we have 2 possible solutions.
1. Remove negative `proximitypriority` on the high trajectory weapons
2. Set this units as an exclusion to the `autoTargetRangeBoost` in the gadget.

**Comment by SethDGamre** [comment]
I'm gonna consolidate these proximityPriority issues into this and seek approval.
https://github.com/beyond-all-reason/Beyond-All-Reason/issues/3807
