### ISSUE TITLE
Build this game on Gentoo

### ISSUE THREAD

**Issue by joostruis** [beyond-all-reason/Beyond-All-Reason#2095]
Not sure how to ask this but I would like to build this game with Gentoo Linux. Is there some overlay or attempt to do this?

**Comment by p2004a** [comment]
It depends what you mean by "build this with Gentoo". Overall, if you think about packaging it so that you download all and can just play without fetching anything additional, that's more or less impossible. To play in multiplayer, all players *must* have exactly the same version of engine, and exactly the same version of the game code, so we can't depend on whatever release cycle distributions have to release those.

What can be packaged rather easily is the launcher component, the component that downloads all the other things: latest config, game, engine and maps on demand.

This is how this is currently packaged for flatpak and some external to project person is maintaining the arch package (that is just repacking provided appimage).

**Comment by joostruis** [comment]
I understand. If packaging would mean that we provide just the launcher that is exactly the same as the flathub or appimage then it would not be worth the effort. Thanks for explaining.
