### ISSUE TITLE
[Client Mod Proposal] - Preserve commands after transport

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/Beyond-All-Reason#2148]
### Short description

When unloading a unit, the command queue it had before being loaded should be reissued as soon as it is unloaded

### Problems this will solve

Currently, when loading a unit into a transport, its command queue is cleared, which makes micromanaging units with transport a lot more cumbersome than it should be, as it needs to be given new orders every time it is unloaded.

**Comment by PtaQQ** [comment]
GDT has approved this proposal with the following feedback / requirements: 
- the widget should ignore move commands so that units don't try to continue going to the rally point after transporting 
- make sure it works with ally units 
- once ferrying is fixed make sure its compatible with the widget
