### ISSUE TITLE
[FR] Clicks should issue commands to minimap if there's an active command and 'left click moves camera' is active

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/Beyond-All-Reason#2203]
### Short description

If there's an active command, say 'Fight', and 'left click moves camera' setting is turned on for minimap, the command should be issues in minimap instead of moving camera.

### Problems this will solve

Players from other games expect being able to issue commands in minimap, this is currently impossible with 'left click moves camera setting' that eats all mouse clicks in the minimap.

They could in theory disable the setting, which behaves as expected, but they might prefer being able to move with left click while retaining the ability to issue commands.

### Proposed Fix

Return early on both mousemove and mousepress [here](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/gui_minimap.lua#L251-L281) when [GetActiveCommand](https://beyond-all-reason.github.io/spring/ldoc/modules/UnsyncedRead.html#Spring.GetActiveCommand) is not nil.

Additionally, another trivial fix to only reset `leftclicked` on MouseRelease [here](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/gui_minimap.lua#L251-L281) if `button = 1`.

**Comment by WatchTheFort** [comment]
If the minimap were conceptually a miniature rendered game view, rather than a special picture, so that interacting with the minimap was exactly the same as interacting with the map when completely zoomed out, but in a smaller area, would there be any problems?

Middle-click to centre view within the minimap would seem to be a good alternate control scheme.

**Comment by sprunk** [comment]
Minimap already is a miniature rendered game view. It's just that left-clicking a random point in the game view deselects your units, which shouldn't happen when people left-click the minimap to move the screen. This is controlled by a setting that turns minimap clicks into movement and which does so very eagerly.

**Comment by icexuick** [comment]
I'd like to consider adding in this feature, that when any command is active, this will be the default.
It's weird that some commands work on minimap, and others not.
Either enable all, or disable all.

**Comment by badosu** [comment]
> If the minimap were conceptually a miniature rendered game view, rather than a special picture, so that interacting with the minimap was exactly the same as interacting with the map when completely zoomed out, but in a smaller area, would there be any problems?
> 
> Middle-click to centre view within the minimap would seem to be a good alternate control scheme.

This is already the case, at some point one year and a half ago it was decided engine default was not good and the left click thing was born.

I'm not against it, but if it's the case that it is to be used as a default it should be refined.

Some players might not like mmb for camera pan and prefer lmb, a more elegant solution would be to be able to bind mouse actions instead from the start so we don't have messy ad-hoc behavior.

**Comment by Jazcash** [comment]
Related: https://github.com/beyond-all-reason/BYAR-Chobby/pull/126

Personally, I think the minimap accepting all inputs as if they were commands is unintuitive. The default behaviour for minimaps in all other RTS games is to allow either left or right click to jump to the clicked location, and interpretting both left and right click as given commands prevents this.

Maybe a reasonable compromise would be left/right click jumping to location if no units are selected. Otherwise, if units are selected, then right click on minimap should proxy the default action (e.g. move cmd), or if units are selected and a command is active (e.g. fight command) then neither left or right click jumps to location, as both have uses (left click issues standard fight command at the clicked position and right click drag issues line-distributed fight commands).

Although, I'm not entirely sure it's safe to assume that most players would not want to jump-to-location if they have units selected and are issuing a command, as maybe they would want to jump-to-location first in order to be able to issue their command through the main camera.

**Comment by icexuick** [comment]
Fair point about unresolving.
PtaQ also mentioned this.

Though I think we can all agree that having only halve of the set of possible commands that can be issues on the minimap is inconsistent / not intuitive. An extra option to disable these clicks for (pro) players would be a good option i think.

**Comment by sprEEEzy** [comment]
_If you have units selected, clicking "Fight" and then issuing that command with LMB on the minimap_ - I don't see how that's not expected behavior for RTS players. If you want to first move the camera via LMB on minimap, you're going to do that without having "Fight" active. Only after moving the camera, you're going to select "Fight" and issue it on the map. 

Currently, the left click on minimap moves the camera, and the selected command just stays selected.

As for using middle mouse, it can be an option, but I'd say most RTS players don't want to use MMB at all because it's clunky and not every mouse can do it consistently. 

Suggested change:
- add new option "commands override left click moves camera"
- commands can be issued via left click on minimap

**Comment by badosu** [comment]
The solution is straightforward, just don't eat left click if there's an active command on minimap widget MouseClick.
