### ISSUE TITLE
Rework Mex Snapping for T2 mexes

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2383]
### Description

Right now, if you're basically forced to use _areamex_ when upgrading to T2 mexes in a pinch. Why?

Because buildings get in the way of putting down blueprints for mexes - which is especially bad for upgrading to T2. Even the T1 mex itself blocks it! The only consistent way to put it down is to place it pixel-perfect on top of the existing T1 mex, which is not feasible in a real game. Same thing happens to Geo, btw.

![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/9e60141e-716c-4bd7-a3df-aab778f8e68c)

If you have a small base with 3-4 mexes within it, good luck trying to upgrade all of them without having many failed attempts due to other buildings blocking the blueprint.

**How to fix?** Make it auto-snap to the nearest mex, regardless of what's underneath the blueprint at the time. 

### Problems this will solve

Will make players not completely dependent on _areamex_ to upgrade mexes.

**Comment by PtaQQ** [comment]
Approved by the GDT, awaiting implementation - decision is to standardize to two values in order to give the mappers some aesthetic freedom, but keep the values consistent across two types of maps: 
1) 130 - standard (planet maps)
2) 70 - low gravity (asteroid, space station, moon maps) 

+ needs a clear indication in the map picker UI that marks low gravity maps

**Comment by thehobojoe** [comment]
This can be closed.
