### ISSUE TITLE
When using Grid layout and constructor is selected, don't display building options without entering building submenus

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#2448]
### Description

![image1](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/9414375/e1337519-8625-4fa5-a3bd-8be6d282e09f)

Currently, when you select a con, the "building quick menu" is shown. This feature is great on Default hotkeys, but it's useless on Grid. You will never click a building with your mouse, as you're using hotkeys. Even if you do, it's going to be some less used building in a submenu.

### Problems this will solve

1. Will not confuse users when entering submenus, in terms of all icons switching places.
2. It will give more screen space for 99% of the game.

**Comment by sprunk** [comment]
Wouldnt "you will never click with mouse" stop being true once grid becomes the default?

**Comment by sprEEEzy** [comment]
I'm not familiar with the exact plans, but in that case you do have a point. I'd love to see an option to turn it off at least, for advanced players.

**Comment by icexuick** [comment]
At the moment there is a pilot test with GRID being set to default for new installs.

We're gathering feedback at the moment, and yes as @sprunk pointed out, we've already gotten some feedback about this. We're expecting that the majority of players will not use buildmenu-shortcut-keys (or possibly any shortcut-keys). 

We already have an issue here, where you need to click the "BACK" button first in order to select the next category, which is very bad UX for new players and players that don't use/want to use shortcut-keys. I've asked @thehobojoe to find a fix for this and move the BACK button to a different location, so you can keep the 4 visual tabs for the categories always visible.

Anyways, I do understand @sprEEEzy and the wish for this to be a pro setting/mechanic.
I think this should/could be an option/setting to disable the initial buildmenu.
This is however a lower priority than fixing the back-button fix, which now forces (new) players to click 8 buttons in order to go through all categories.

**Comment by thehobojoe** [comment]
This is enough of a niche request that I will reject making an option out of this, this kind of thing is best handled with custom widgets, which I have done here: https://discord.com/channels/549281623154229250/919126039639252992/1245947234558808106

**Comment by Ape** [comment]
I see this is an old, rejected feature request, but I'd actually really like this option.
