### ISSUE TITLE
Problem with Graphics

### ISSUE THREAD

**Issue by wcharfi** [beyond-all-reason/Beyond-All-Reason#2678]
Hello,

First i want to thank you for the développement of this powerfull game. My problem is that i dont see units firing and building there is like 1 week ago before that it was working ok, and when i try to see some old saved games it works ok too. Probably after an upgrade of BAR this period i have this problem.

I add some Screenshots joinned.

Best regards

![UNITS_FIRING](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/74784360/a194fc24-bb52-466c-bc3e-0df7feccb53f)
![Construction lite](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/74784360/4bd7c011-8855-4a10-a38b-edd93e8ef76a)

**Comment by jbazant** [comment]
I have the same problem (also occured in the last week). I am using flatpack version on Linux Mint. 

To me it looks like the layer with projectiles is hidden behind the terrain, because it can be sometimes partialy visible when I change zoom / camera angle. And sometime I can see the sharp edge beteeen where particles are visible and where not. Or maybe wrong render order in pixel buffer? (I am not game developer, so take this just as hint from someone who has a little experience with WebGL and some school and outdated experience with OpenGL)

**Comment by andrejpekarcik** [comment]
Hi, 

fired projectiles from battle units and energy streams from builder are seldom seen. Difficult to play almost impossible.

**Comment by jbazant** [comment]
Probably relates to https://github.com/beyond-all-reason/Beyond-All-Reason/issues/2677. (Or even duplicate)

**Comment by wcharfi** [comment]
Yes it is a duplicate sry didn t see this, it's the top half of the screen that dont work like the description in #2677 i just tested it.

**Comment by eode** [comment]
This issue should be closed in favor of #2677
