### ISSUE TITLE
target list + burst = op

### ISSUE THREAD

**Issue by MeSaber** [beyond-all-reason/Beyond-All-Reason#2776]
### Description

The Razorback works the same that it can instantly find a new target inbetween bursts so it can utilize the full burst, Thor cant really do this as it need to aim gun, but making a list overrides:

https://i.imgur.com/MqX3v66.png
https://i.imgur.com/LIjgx58.png
https://i.imgur.com/6ZsYpXQ.png

### Expected Behaviour

Should only be able to deliver the full burst in a small arc in gun direction.

### Actual Behaviour

360 arc.

### Reproduction steps

attack circle or set target circle.

**Comment by thehobojoe** [comment]
Moved to engine https://github.com/beyond-all-reason/spring/issues/1451

**Comment by marcushutchings** [comment]
Why is this issue closed before it is resolved? It should wait until the engine ticket is resolved and then test in BAR again to confirm that it resovles the issue for BAR. There may be other factors on BAR's side involved - also, closing this issue here may create the false impression that the issue is no longer present in BAR.

**Comment by thehobojoe** [comment]
I closed it to make it clear that this isn't where the issue will be tracked. I am happy to reopen it.
