### ISSUE TITLE
Way to save/edit alt-key groups to a config file

### ISSUE THREAD

**Issue by dannyhannyford** [beyond-all-reason/Beyond-All-Reason#3019]
### Description

Similar to how people have `uikeys.txt` that they edit, have a file that shows your current alt-key groups, and allow it to edit them via the file.

This will allow players to save their alt-key groups and avoid them being deleted after new patches.

### Why?

Have your alt-key groups deleted is frustrating. I would assume this is preventable as alt-key groups persist between games, until after a patch.

### What area of the game does this feature request pertain?

Settings, Controls or Hotkeys

**Comment by salinecitrine** [comment]
> Similar to how people have uikeys.txt that they edit, have a file that shows your current alt-key groups, and allow it to edit them via the file.

These can be found in `<Beyond-All-Reason>\data\LuaUI\Config\BYAR.lua`, along with most other settings. Search for `["Auto Group"] = {` to find the auto group settings.

Keep in mind it's possible to break your settings by editing this file, so make a backup if you do. It's also probably best to edit it while a game isn't active, so your changes aren't overwritten by the game on exit.

> Have your alt-key groups deleted is frustrating

If you're encountering a bug, you'll probably get more help on discord (`#support-bugs` channel), since it's checked more frequently, and by more people.
