### ISSUE TITLE
Remove the abusive Boss "Block" feature

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3412]
### Description

_This is related to Chobby and Website, but it's also a "philosophical" issue, so I'm not entirely sure where to put this._

Currently, you can "block" someone thru the website, and then that player cannot join lobbies that you're a boss in. The feature exists to allow folks to not have someone (or multiple individuals) constantly "invade" a lobby. 

### Why?

This feature is bad for multiple reasons:
- the block is infinite, it doesn't expire
- most players that use the block feature aren't even aware of this byproduct
- players that are aware, abuse it vs those they hold personal grudges against
- banned players cannot even spectate games in that lobby
- boss is required in lobbies because a lot of commands aren't voteable, making it easy for the player abusing this to hide his intentions
- it's not transparent -> other players in the lobby are:
  - unaware who's on the boss' block list
  - unaware who tried to get in and got denied
  
Why it's not needed:
- you can use kickban to "ban" someone for 15 minutes, it's one click for the boss. There aren't thousands of players trying to get in your lobby. Bossing or just community kickbanning does the job.
- players are aware that someone got kickbanned, which may or may not trigger a response (unlike now, where they're unaware)
- the playerbase is so small, that barring someone from joining one or two active lobbies of same type effectively means they cannot play the game (decided by two individual players)
- even game moderators allow appeals for bans they issue, and people eventually get unbanned. Being barred from playing, because of this feature, feels more unfair than getting banned for being e.g. racist in BAR

### What area of the game does this feature request pertain?

Other

### Other (optional)

There's another version of this feature that is related to total amount of players in the lobby having one person blocked. This might need a second look too, as I don't know what kind of majority is needed.

**Comment by p2004a** [comment]
> boss is required in lobbies because a lot of commands aren't voteable, making it easy for the player abusing this to hide his intentions

This is the problem here. The problem is that all regular lobbies should just not require boss, that's it. If you are a boss of a lobby, you have infinite power over it, if you have personal grudges against somebody you don't want to play with, yeah, not allowing them in lobby you are boss of is totally reasonable.

**Comment by sprEEEzy** [comment]
> > boss is required in lobbies because a lot of commands aren't voteable, making it easy for the player abusing this to hide his intentions
> 
> This is the problem here. The problem is that all regular lobbies should just not require boss, that's it. If you are a boss of a lobby, you have infinite power over it, if you have personal grudges against somebody you don't want to play with, yeah, not allowing them in lobby you are boss of is totally reasonable.

I suggest the feature gets removed until the adjustments are made. 

Jauggy proposed to make a voted-in boss different from the original lobby boss, in a way that his block list wouldn't get applied.

**Comment by MeSaber** [comment]
> > boss is required in lobbies because a lot of commands aren't voteable, making it easy for the player abusing this to hide his intentions
> 
> This is the problem here. The problem is that all regular lobbies should just not require boss, that's it. If you are a boss of a lobby, you have infinite power over it, if you have personal grudges against somebody you don't want to play with, yeah, not allowing them in lobby you are boss of is totally reasonable.

A regular lobby is actually someones private lobby in the first place, there are no 'public lobbies' by definition. If i make a server dont i wanna be boss over it? Why should it be a regular lobby? What decides when it becomes 'regular/public'? The player amount?

Personally i dislike all this power over banning people from games just as spreezy explains it can block a player from not playing the game completely which is insane power to have.

I would remove all these avoid/block features because no game that has had a thriving community has had this power like starcraft for example. We all get along with some grudges without having to ban ppl from playing the game.

If you wanna fix this issue then fix the chat instead, stop ppl from saying abusive stuff and trigger ppl. More restrictive chatting because chatting except for strategy isnt really required. If this game is your personal life, well then there is a bigger issue at hand and it shouldnt affect the playerbase.

**Comment by stanisk223** [comment]
Having setup the wacky lobby back in the day I require the ability to block persons.

I'm playing the game for fun; I'm setting up the lobby with a particular set of settings.
The people I blocked were:
rude for no reason; usually they were told by someone "hey; that behaviour isn't acceptable here" and then continued
griefed. i don't care why who did who and what to when in the last game so you decided to reclaim their mexes. i'm running the lobby and don't have any tolerance for it; so g'bye.

I'm sorry that this doesn't seem to work for people being blocked out or limited from playing the lobby they want to in a small pool of players.

if certain commands require Boss but can have that retquirement removed .. fair enough.
if someone wants to boss and create a lobby experience; they need controls to do that. which requires a balance somewhere.

**Comment by Ruwetuin** [comment]
There have already been boss changes implemented to address this
