### ISSUE TITLE
Improve laser unit accuracy to increase consistency of their counter role against ticks

### ISSUE THREAD

**Issue by sprEEEzy** [beyond-all-reason/Beyond-All-Reason#3462]
### Description

Currently, laser units like Grunts and Centurions can miss up to 10 shots in a row on a moving tick within their range, even when not running around max range.

https://github.com/user-attachments/assets/188910c5-dacf-4b0b-b933-c8adab68b987

### Why?

They already have damage drop-off, I don't think there should be a reason for such heavy RNG in their shooting against an already insane unit like the tick.

### What area of the game does this feature request pertain?

Gameplay

**Comment by sprunk** [comment]
> oriented around precision

but the request is about accuracy

![image](https://github.com/user-attachments/assets/ff631ef1-d999-4aa4-9619-60ff689eb2c1)

**Comment by MeSaber** [comment]
This is one for the GDT to figure out whats best because having grunts with 100% accuracy is very op for micro. Some small percent of randomly missing is healthy for the game, but ofc it shouldnt be 10 shots in a row. Maybe 5-10%.

**Comment by WatchTheFort** [comment]
Approved by GDT. Currently implemented as a modoption for testing https://github.com/beyond-all-reason/Beyond-All-Reason/pull/3467.

**Comment by Rimilel** [comment]
Can the grunt dps just be nerfed slightly if that's the case? Grunts good for hitting mobile targets, thugs and rockets for stationary ones?

**Comment by MeSaber** [comment]
So the grunt is trading well vs pawns and other units imo and this is because it doesnt miss bigger targets, its only tick/rascal/rover that it has trouble aiming at, so by making it never miss those targets, grunts will be op vs them, but it doesnt change the interaction with other units like vs pawns/incisor/etc.

I dont really feel grunts is 'op' in terms of dps, they still need to get very up close to even use their full dps. But im not in GDT so i have no say in the matter :)

Will be fun to see how grunt vs tick interaction without miss chance. Im betting they cannot lose vs ticks now.

**Comment by SethDGamre** [comment]
being that this is a modoption and there's a game design team / game balance team thread on discord for discussing this issue internally, can this issue be closed?

**Comment by PtaQQ** [comment]
It can be closed
