### ISSUE TITLE
Freeze on Zorin OS with Fontconfig error

### ISSUE THREAD

**Issue by Toasterson** [beyond-all-reason/Beyond-All-Reason#3884]
### Description

I am getting a freezing game but launcher is fine.

### Expected Behaviour

It works :)

### Actual Behaviour

Freeze with the logs https://log.beyondallreason.dev/logs-20241026T2009-A5eY2tVe.zip

Main lines I think are the culprit
```
[t=00:00:00.653195] [GR::LogDisplayMode] display-mode set to 1920x1044x24bpp@60Hz (windowed::decorated)
[2024-10-26 19:51:56.022] [info]  [t=00:00:00.964525] [TexMemPool::Resize] poolSize=536870912u allocSize=0u texCount=0u
[2024-10-26 19:51:56.022] [warn]  Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "description"
[2024-10-26 19:51:56.023] [warn]  Fontconfig warning: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 5: unknown element "reset-dirs"
Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 6: invalid attribute 'salt'
Fontconfig error: "/etc/fonts/conf.d/05-flatpak-fontpath.conf", line 7: invalid attribute 'salt'
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
[2024-10-26 19:51:56.023] [warn]  Fontconfig warning: "/etc/fonts/conf.d/10-sub-pixel-none.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-yes-antialias.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "description"
[2024-10-26 19:51:56.023] [warn]  Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
[2024-10-26 19:51:56.023] [warn]  Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
[2024-10-26 19:51:56.024] [warn]  Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
[2024-10-26 19:51:56.024] [warn]  Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
[2024-10-26 19:51:56.024] [warn]  Fontconfig warning: "/etc/fonts/conf.d/48-spacing.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/run/host/font-dirs.xml", line 4: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 4: invalid attribute 'as-path'
Fontconfig warning: "/run/host/font-dirs.xml", line 5: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 5: invalid attribute 'as-path'
Fontconfig warning: "/run/host/font-dirs.xml", line 6: unknown element "remap-dir"
Fontconfig error: "/run/host/font-dirs.xml", line 6: invalid attribute 'as-path'
Fontconfig error: Cannot load config file from /run/host/font-dirs.xml
[2024-10-26 19:51:56.024] [warn]  Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
[2024-10-26 19:51:56.026] [warn]  Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
[2024-10-26 19:52:01.799] [error] Spring failed with code: null
```

### Reproduction steps

1. Install game via Flatpak on Zorin OS 17 (Ubuntu plus custom packages but no base updates)
2. start game

**Comment by saurtron** [comment]
I managed to reproduce you issue, it seems to be because of older fontconfig spring is compiled against by the team (2.12.6, from the ubuntu 18.04 build system). Note the crash could be because of some other library instead of fontconfig, and fontconfig being just the noisiest.

In my case (ubuntu 24.04), this happens when I run the game built with the docker-v2 spring build system directly.

In my case, however, when I run the flatpak version it works fine, since it ships it's own libraries afaik. It's a bit strange in your case it doesn't work with flatpak. I also didn't have problems with older ubuntu versions where I also run through flatpak in the past.

If you can, it'd be nice to have the result of `dpkg -l libfontconfig1` for your system, and specially the result of `flatpak list`. You could try running `flatpak update` to see if it helps.

The root cause seems to be the binaries provided by the team atm are quite outdated, so not very compatible with recent linux versions. That can take some time to fix and require a lot of testing :P.

**Comment by Toasterson** [comment]
Yes that is true, Discord was a bit more active and faster and came to the same result. Ultimately I ended up running a distrobox with Arch as this seems to impact Most ubuntu releases but not arch. Somehow the mounted /etc/fonconfig files and the libraries are out of sync and if flatpak does not emulate /etc/fontconfig it still gets to that problem. For some reason arch seems to have solved this. Anyway, many on discord recommended distrobox and I have to say, it really helps hoe BAR. I heartly recommend running a distrobox with arch for BAR. Very solid experience.

**Comment by saurtron** [comment]
Well, I think it's mostly a coincidence. I have ubuntu 24.04 and it works for some reason, I think because I don't have so much stuff in flatpak or it's a system flatpak install instead of user.

Anyways, a fix that should work for everyone is in the works hopefully will be live on the next engine release and won't depend on specific os or running method.

Also I think setting the env var "export FONTCONFIG_FILE=foo.xml" can be a workaround for those experiencing the issue, but that's quite tricky to set when running with the flatpak launcher. (and without the launcher it will crash because of chobby issues too lol).
