### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by fengluo2** [beyond-all-reason/Beyond-All-Reason#3983]
### Description

use NuttyB Raptors 1.52 mod and adjusted some options.
log: [20241130181736_infolog.txt](https://github.com/user-attachments/files/17966374/20241130181736_infolog.txt)

### Expected Behaviour

no clash

### Actual Behaviour

has clash

**Comment by saurtron** [comment]
Checking the logs here, there is indeed a crash towards the end (line 46737): `D:\Program Files\Beyond-All-Reason\data\infolog.txt" msgCaption="Spring: Unhandled exception" mainThread=1`

There's not very useful information about where that's coming from though.

Other than that, I see some lua errors:

- `[Internal Lua error: Call failure] [string "LuaRules/Gadgets/unit_evolution.lua"]:352: attempt to index field '?' (a nil value)`
  - already taken care of by #3998
- `[Font] Error: called End() without Begin()`
  - tricky to know where this is coming from since we get no lua line number. I see some suspicious Begin/End usage at AtlasOnDemand and QuadTreeAtlas but likely not that. Will check again to see if I see smth else, but finding a mismatching font begin/end is like finding a needle at a haystack.

All in all, beyond checking those lua errors I don't think this report gives us enough information to know what happened, although maybe someone else can interpret and debug the stacktrace information, but it's just some hex offsets into spring.exe and I have no idea how to interpret or use that.
