### ISSUE TITLE
Disallow transporting allied commanders with air transports

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/Beyond-All-Reason#430]
As its used more for trolling, and I cant think of an actual use case where its genuinely useful

**Comment by WatchTheFort** [comment]
What does the title mean?

**Comment by sprunk** [comment]
I think it should be "disallow transporting allied commanders"?

Alternatively, "allied enemy" could mean the temporarily allied enemies in FFA (in which case you probably don't want to allow your """ally""" to transport your commander either).

**Comment by KyleAnthonyShepherd** [comment]
This issue was brought up in the discord a short while ago. 
Transporting allies commanders can be useful with coordinated teams, but enables trolling in casual teams.
My suggestion was to auto-share the transport to the commander's team. So if Player 1 picks up Player 2's commander, the transport is automatically shared to Player 2

**Comment by SethDGamre** [comment]
this issue is a big problem in the early game with transport rushes. The upcoming transport rework is going to render this a non-issue because it'll be much later in the game before it can happen. The balance team has had all this time to prevent this (with a very simple gadget) and they haven't which tells me this isn't a wanted feature.
If it is wanted, I can write a gadget for it in 5 minutes. 
Close it, or ask me to make a gadget.

**Comment by SethDGamre** [comment]
We now have medium transports which are intended to address this issue. It's actively being worked on to achieve the ideal amount of commander drop cheese strats.

I think it's safe to say this issue is resolved.
