### ISSUE TITLE
Nano turrets

### ISSUE THREAD

**Issue by Sutrinc** [beyond-all-reason/Beyond-All-Reason#557]
Hi All.

Maybe it is possible to do  to upgrade the nano turrets. t1 - t2 - t3. more building strength and more radius. this is necessary in order not to build turret fields, and to save space. it will not affect the balance, but it will be more convenient and beautiful.

Thank you for the attention

**Comment by Goopy16204** [comment]
It would likely alter how the game is played. There would be a larger focus on increasing economy more easily because you could respond to threats faster. I believe that is not currently the way the game is trying to go.

**Comment by Jazcash** [comment]
Building "upgrades" is something that we've kept out of BA/R for a long time despite almost every other spin-off incorporating it in some way, can't say I'm a massive fan of it as a concept and prefer more elegant solutions, e.g. stackable nanos (not my idea).

Also, on the topic of building upgrades, mexes could be "upgraded" in the same vein by making T2 extractors neatly fit around/on top of T1 mexes - again not my idea but I thought it was a cool suggestion.

**Comment by WatchTheFort** [comment]
> 
> Also, on the topic of building upgrades, mexes could be "upgraded" in the same vein by making T2 extractors neatly fit around/on top of T1 mexes - again not my idea but I thought it was a cool suggestion.

That has already been implemented and is currently in the game.

**Comment by sprunk** [comment]
> will not affect the balance

 * by increasing build radius you're potentially enabling things like building/repairing from behind a cliff on certain maps
 * large nanoturret fields are purposefully so because then it's easier to scout them, make them chain-explode, and they require the player to put thought into their base layout.

> beautiful

Don't BAR aesthetics lean on the "lots of units" kind? A base with 20 smaller nanoturrets looks more "alive" and busy than just one big nanoturret.
