### ISSUE TITLE
curl Problem with the SSL CA cert with Fedora 35

### ISSUE THREAD

**Issue by Jed28** [beyond-all-reason/Beyond-All-Reason#588]
```
byar:test: [Error] /home/runner/work/spring/spring/spring/tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:81:DownloadUrl():Error in curl Problem with the SSL CA cert (path? access rights?) (error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/cert
```
I used the fix from this bug report [Symlinking /etc/ssl/certs/ca-bundle.crt -> /etc/ssl/certs/ca-certificates.crt](https://github.com/beyond-all-reason/Beyond-All-Reason/issues/129)
This bug report has been marked as fixed and closed but the bug persists. I used the latest appimage "Beyond-All-Reason-1.1252.0.AppImage"

**Comment by spawel44** [comment]
I have the same error with Fedora 35 and BAR AppImage.

**Comment by AngryPenguinPL** [comment]
Yes, issue is still here. I use OpenMandriva and in last year I had to symlink to the certificates to start the game download in the launcher. I thought they fixed it since the bug was marked fixed.
Now, on a fresh installation of the system, I can see that the same problem appeared again... This means that the bug is not fixed.

My distro keep cert file here: `/etc/pki/tls/certs/ca-bundle.crt`
so in the same place as Fedora, mageia, RockyLinux, ALTlinux, AlmaLinux, RedHat, AmazonLinux, CentOS or Rosa Linux.

**Comment by p2004a** [comment]
The issue is in the https://github.com/beyond-all-reason/pr-downloader component, I will look into it. The problem is not obvious though as visible in this thread: https://curl.se/mail/lib-2022-05/0038.html, need to do more research, including why the current fallback in the pr-downloader doesn't work properly on those systems.

The main workaround for users that face this issues atm are:
- use flatpak version
- symlink system certs to different location as mentioned in first message
