### ISSUE TITLE
Enable tanks to drive backwards on skrimishing

### ISSUE THREAD

**Issue by lweberk** [beyond-all-reason/Beyond-All-Reason#60]
This would make skirmishing a lot richer and realistic. At the same time it would have bigger impact on gameplay for which I would like to have your tentative approval first. @Ruwetuin @icexuick (sorry if I'm missing anyone else on the sign-off list).

I managed to get it working on the stumpy already and know my way around.

* [ ] Get approval
* [ ] Make listing of all tanks in question

**Comment by Beherith** [comment]
Just an FYI, there is already front, side and rear armor modifiers built in to engine, as afaik, it is on by default in BAR. Also, I am against tanks reversing, they would encroach too much on kbot roles.

**Comment by lweberk** [comment]
Yes, the point is making use of them. No, BAR does not differentiate.

As for reversing, it makes tank skirmishing meaningful. Currently they behave totally atypical. No tank wastes time by turning around because it intends to back up a few meters to maintain contention and the turret straight to the enemy line.

I do not see how it would conflate them in their role with bots? They still behave very differently.

If you add in armor differentiation, you also stress on that point. You cannot turn around and just to keep distance while skirmishing without expecting to incur extra damage and losses.

They both go hand in hand. Arguably backing up is something that is useful on its own though.

**Comment by PtaQQ** [comment]
We have tried this, reverse movement was possible and automatic when the destination was set close to the back. The movement was a small fraction of the front speed. 

Even with this very delicate approach most tanks became tremendously overpowered. Arty, penetrators and other stuff that can only shoot forward was even more op. But even general tanks like stumpy were too strong as the ability to move back without slowly turning in place has made them really invincible. I reckon that it would have to come with a big vehicle stats readjustment and Im not sure if we want to lose and have to re-tune the current close to ideal balance state.

**Comment by MasterBel2** [comment]
I fear that calling stumpies "invincible" is a misrepresentation. What happens when you have Stumpies v.s. Stumpies?

I'd love reversing vehicles, and if damages had to be nerfed for that, so be it. Or if costs had to increase. 

I don't build penetrators because they're the most frustrating unit in the game. And banishers can shoot backwards, penetrators can't? 

I feel that if holding true to the TA legacy, it's somewhat a natural extension for vehicles to be able to roll backwards, and yes it would take a tonne of balance to make it work but I feel like it's worth it.

Maybe it's a goal for somewhere down the line, though. Because that sort of rebalancing wouldn't be simple.

**Comment by Ruwetuin** [comment]
moving backwards effectively increases dps because turret doesnt have to move/reaim.

We tried, it was awesome, but hard to balance without nerfing unit stats across the board. Enough other stuff to do to give it the full dedication this implementation would require.
