### ISSUE TITLE
Differentiate front, side and rear armor values for tanks

### ISSUE THREAD

**Issue by lweberk** [beyond-all-reason/Beyond-All-Reason#61]
It comes as a natural consequence of #60

**Comment by icexuick** [comment]
We have discussed this before - and afaicr we decided to not go there.
It would add yet another variable and 'system' to learn and use.

Though it might still be active on some units as i recall that we did test this a month or two ago.
Personally i would not go here. The huge amount of units in BAR is, even for pro's, hard to learn and master in itself.

I'd also like to know how much this can affect performance, which i really like to be as high as possible, and rather remove some (overkill) sim-stuff to support larger maps/battles, than to focus on more micro and more sim-stuff.

**Comment by lweberk** [comment]
You are right on the adding of complexity, and the game being complex as-is. 

In terms of learning, it is not something that adds to the steepness of the curve, while giving a tremendous boost to the feeling of realism. You can see this feature very clearly in-game and it is one of the more intuitive things you get right away.

Performance wise its cheap-ish. It is not the place you can shave off sim-time. I'd like to back that statement up with some hard facts though.

**Comment by fruehling76** [comment]
the question is also: what would u gain from it? is it really possible to micro in grand scale with hundred units to particularly force attack on a certain side of a unit? and what will happen if one side is down? unit dead? then u have to retune also hp or dps again. i am doubtful about this. imo its more sth for tbs games or rts with few units

**Comment by PtaQQ** [comment]
It's more about cool micro plays and also penalising retreating more

**Comment by MasterBel2** [comment]
I'd be cautions about penalising retreating more, considering that there are a number of mechanics which currently encourage retreating. AKA such a change could really change the way the game is played, in theory. 

Note that there are also (invisible) damage buffs for when a unit is surrounded, iirc of up to 50%. I don't know specific details on the mechanics.

Nerfing retreating runs the risk of nerfing certain kind of micro too, so such as, well, retreating. Touch-and-go micro (esp. with units like Janus) is already dicey enough, and units in retreat

Retreating units also have something of a range buff currently, and advancing units have something of a range nerf iirc, due to engine mechanics. Adding armour would potentially mess with this already delicate balance – possibly making it more interesting, possibly just changing the area of interest.

What do you want battles to look like? Everyone goes in and then they don't come out again ever until the game is over? The person who goes in with the advantage will win almost every time. Falling back to cover, in an extreme scenario, might not even be worth it.

I just think we should be careful.
