### ISSUE TITLE
Rezbots reclaim before repairing on patrol

### ISSUE THREAD

**Issue by lweberk** [beyond-all-reason/Beyond-All-Reason#62]
Should they do it the other way around?

**Comment by icexuick** [comment]
Perhaps make this automated... when not e/m stalling too much, go for repair first.
But with high metal-request-pull - do reclaim first.
Or do a combination of repairing really damaged units (below 25%) first, then reclaim.

**Comment by lweberk** [comment]
That is arguably too smart. The player will experience a mixture of behaviors and not know what to expect. Specially if the intention is to have them as repair bots in a littered battlefield.

The last one is a good one. Repair below 25% and then move on to reclaim. Its simple and consistent.

Another possibility would be to extend behavior of the reclaim command to move-reclaim on right-click, leaving left-click to area-reclaim. Dunno. I'm in the dark on this one. No idea if the engine allows for such behavior. I'll be investigating current modifier gadgets to see what is possible.

**Comment by fruehling76** [comment]
agree - they should repair before reclaim

**Comment by PtaQQ** [comment]
Guys this whole ticket is uninformed. Patrol is supposed to work this way. If you want repair before reclaim use Fight.

**Comment by sprunk** [comment]
How are people supposed to get informed about this?

**Comment by PtaQQ** [comment]
With guides, and in-game tutorial missions. 

Both behaviors are desired in given situations. If you make them the same you will lose the possibility of one of them.

Other way could be to make them the same as you said, but add modifiers like right now alt+F making rezzers heal and resurrect instead of reclaim. so ctrl for example would flip the healing/reclaiming priority. But Im afraid this is an equally obscure mechanic. Opinions?
