### ISSUE TITLE
Missing names for rocks

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#672]
![4](https://user-images.githubusercontent.com/89547444/147551691-1446fe8a-7073-436c-900f-0621a5961855.JPG)
Probably problem somewhere in commits f80674b-88a3678
![3](https://user-images.githubusercontent.com/89547444/147551688-9e50e49e-07c6-4cf5-997d-376f951c806f.JPG)
Map tropical-v2

**Comment by 6AKU66** [comment]
[infolog.txt](https://github.com/beyond-all-reason/Beyond-All-Reason/files/7784020/infolog.txt)

**Comment by icexuick** [comment]
This map should be remade.

**Comment by WatchTheFort** [comment]
This happens for map features that were missed when compiling `language\features_en.json` and `gamedata\map_feature_i18n_proxies.lua`.

Right now the log echoes what key is missing a translation, and I can add an echo to the log for what they should be, so that we don't have to go hunting through every map.

**Comment by WatchTheFort** [comment]
I have added logging for map features missing I18N entries. These logs _should_ be automatically submitted to the server, so that they can be collated and the entries added to features_en.json.

**Comment by KyleAnthonyShepherd** [comment]
![image](https://github.com/beyond-all-reason/Beyond-All-Reason/assets/44480662/9f9d1e20-3e34-4bbb-a51d-94902f8878cd)
Looks fixed to me, closing
