### ISSUE TITLE
Unit's icons dissappear under certain angle of view

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#689]
Map quicksilver remake 1.24

![screen00078](https://user-images.githubusercontent.com/89547444/147987197-eac11fb7-8e31-4242-9350-07103441c056.jpg)
px = 4633.33643
py = 506.462372
pz = 4168.31689
dx = -0.6815894
dy = -0.0635075
name = fps
fov = 90
mode = 0
dz = 0.72897369
oldHeight = 416.165344
|
![screen00079](https://user-images.githubusercontent.com/89547444/147987285-bb95c3fc-29fc-4b16-8c17-0fa60cb59c64.jpg)
px = 4633.33643
py = 506.462372
pz = 4168.31689
dx = -0.675211
dy = -0.1502895
name = fps
fov = 90
mode = 0
dz = 0.72215176
oldHeight = 416.165344

**Comment by 6AKU66** [comment]
@lhog I opened another ticket instead of discuss this problem in closed one.

**Comment by lhog** [comment]
Thanks dude.

On your screenies it could be so that slightly different camera position triggers icons drawing. Unsure about that, but I was able to reproduce another issue that usually happens at oblique camera angle.

![screen02184](https://user-images.githubusercontent.com/1476261/147994048-707089f6-b134-4e0a-a85f-ed124188a569.png)

![screen02183](https://user-images.githubusercontent.com/1476261/147994044-8afe6d71-8d8b-4c3c-b86b-b614c427167b.png)

The implementation tries to guestimate some kind of average view distance and it does so by tracing a ray along the camera main direction to the terrain. In case camera is low, mountain features might become the first terrain point such ray hits and in that case the implementation thinks that the distance to the ground is rather low, so icons are not drawn. This was done (I assume) to make icons turn off and on more or less uniformly and not individually like it was the case with old icons. This issue is fundamentally hard to solve as new estimation of what "average" view distance is will be needed.

**Comment by lhog** [comment]
Yesterday I tried to rectify the issue, but couldn't achieve any success. So we either stay with the current system or switch to individual per-unit icons toggle (like it was the case with old icon system).
cc: @icexuick @Ruwetuin

**Comment by Ruwetuin** [comment]
i guess only on heavy tilted angles you dont experience with actual play, so not really a problem.
