### ISSUE TITLE
performance optimization aircrafts

### ISSUE THREAD

**Issue by fruehling76** [beyond-all-reason/Beyond-All-Reason#76]
lets make fighters aa online. hundreds of fighters shooting missiles to the ground doing relatively low damage each can be quite performance heavy for a relatively small gain. sure hundred fighters do some damage in the end but the price for this is high and imo unnecessary also in term of consisteny when thinking seperating task for unit. fighter is already very powerful in his role and and multirole units should be generally less effective. its only for lazyness keeping ag missiles for fighters but its not even fitting the rest of the game mechanics

as a return for the air-ground balance i would increase hp of gunships a bit for not making everything even more ground dominant. they are still rarely used in general and giving them a small incentive for loosing fighter ground attack ability (having the whole picture in mind) would be probably a plus for the whole game mechanics

cheers, Flaka (if anyone wonders who fruehling76 is)

**Comment by icexuick** [comment]
I think i could agree - never used air ag weapons for anything really useful/important.

**Comment by Ruwetuin** [comment]
First... I dont think any substantial perforformance will be gained with this.
For a lot of people it's a convenience to use mass fighters to target metalmaker/nano groups when the bombers arent there anymore. But this is incredibly lazy/unprepared from the attacker.
For me fighters just being aa makes more sense indeed. UI wise its nice as well since they wont accidently lock-target on on ground stuff, you can even area target air. This has my vote.

**Comment by Ruwetuin** [comment]
implemented in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/3332667a2d735fed779166bd39239c6df8f851c6
