### ISSUE TITLE
Commander's tombstones visible even if it's disable

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#795]
https://youtu.be/Qt_yeY3l7sI
![изображение_2022-02-16_031644](https://user-images.githubusercontent.com/89547444/154171947-3c93dfa3-c6ab-4027-a80b-ca4cad29f940.png)

**Comment by Ruwetuin** [comment]
partially fixed in https://github.com/beyond-all-reason/Beyond-All-Reason/commit/75b6fdca90a9e848cb12bfe7abd020736a958d01

having cus (settings: gfx: Advanced Model Shading) disabled will show them

it uses function gadget:DrawFeature(featureID, drawMode) and set gl.Scale(0,0,0) but this aperently needs cus.
Anybody knows a better way of making a feature dissapear locally?

**Comment by Beherith** [comment]
Maybe gadget unsynced call:
Spring.[SetFeatureNoDraw](https://springrts.com/wiki/Lua_UnsyncedCtrl#SetFeatureNoDraw) ( number featureID, bool noDraw )
return: nil

    LuaGadgets only!

**Comment by Ruwetuin** [comment]
tombstones are no longer toggable
