### ISSUE TITLE
Map edge extension visual glitch

### ISSUE THREAD

**Issue by MasterBel2** [beyond-all-reason/Beyond-All-Reason#988]
Edge extension doesn't take map deformation into account
![screen00277](https://user-images.githubusercontent.com/39206414/170135035-ee5f7ff3-22b3-4e3c-9c90-ad8f01e174f9.jpg)

**Comment by 6AKU66** [comment]
Are you sure?
https://youtu.be/Elieg7h7Cfw

**Comment by 6AKU66** [comment]
Are you sure about?
![2022-05-25 16-07-25 mp4_snapshot_00 06_ 2022 05 25_16 11 22](https://user-images.githubusercontent.com/89547444/170270102-50f546d8-0882-4a08-bc8a-8b095c31e3e2.jpg)
![2022-05-25 16-07-25 mp4_snapshot_00 28_ 2022 05 25_16 11 39](https://user-images.githubusercontent.com/89547444/170270125-cde7485d-f441-4b72-936e-0cf3487b1c17.jpg)

**Comment by MasterBel2** [comment]
Try rotating the map so that the border is on the bottom edge of the screen - that should make the cutoff clearer

**Comment by lhog** [comment]
Make sure you use GL4 version of the widget?
Also it's good idea to always include infolog.

**Comment by icexuick** [comment]
Shouldn't we close issues if they are resolved with latest/default settings?

**Comment by lhog** [comment]
Have we got the confirmation the glitch was on the old widget?

**Comment by MasterBel2** [comment]
I guess it comes down to whether this is expected behaviour. Personally I don't like that deformation can result in areas of the map being hidden, in edge cases like this.

**Comment by lhog** [comment]
> Make sure you use GL4 version of the widget.
Also it's good idea to always include infolog.

Still no clarity on these two and therefore I still have no idea what kind of widget you're dealing with. Old and new widget have completely different implementations. And the lack of deformation would be an expected behavior in one and anomaly in the other.

I'm closing this one with the hope to get proper bug report that includes necessary data. Reopen or make a new one.
