### ISSUE TITLE
Error after switching water type to dynamic

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/Beyond-All-Reason#992]
[t=00:04:17.933000][f=0034142] Set water rendering mode to 2 (dynamic)
[t=00:04:17.940000][f=0034142] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=DrawOpaqueUnitsLua trace=[Internal Lua error: Call failure] [string "LuaRules/Gadgets/cus_gl4.lua"]:1512: attempt to index field '?' (a nil value)

**Comment by 6AKU66** [comment]
It's possible to trigger this error with starting Self-D any unit.

**Comment by Damgam** [comment]
Yet another reason why Bumpmapped is our water of choice

**Comment by SethDGamre** [comment]
Testing requested to see if this bug is still present or if the settings menu option is even still there

**Comment by saurtron** [comment]
1. The settings menu option isn't there, seems it was removed at a21960ffec779a8fc743593b8a30d1f3a2548b50, can still be activated through /water 2.

2. Couldn't reproduce, either activating water 2, or self-d'ing a unit.

Maybe the bug isn't there any more, cus_gl4 has changed since this was reported, so the reported line doesn't match, I think it was ` drawpassstats[drawPass].batches = batches` (see [cus_gl4 back then](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/83e42197c64171f118f754a05dedbcd745bcdabb/luarules/gadgets/cus_gl4.lua#L1512)), and that line is [currently commented](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/ef0ed397fc27c0feb9556c7e0f4f8a2af9bdd323/luarules/gadgets/cus_gl4.lua#L1688).

All in all this bug looks pretty obsolete.

**Comment by SethDGamre** [comment]
Thanks for the research, brother.
